object CheckCommand "hwgroup" {
        command = [ PluginContribDir + "/check_hwgroup" ]

        arguments = {
                "-H" = {
                        value = "$hwgroup_hostname$"
                        description = "Hostname or IP of the device ($CHECK_HWGROUP_HOST)"
                }
                "-p" = {
                        value = "$hwgroup_port$"
                        description = "Port of the device ($CHECK_HWGROUP_PORT)"
                }
                "-w" = {
                        value = "$hwgroup_warning$"
                        description = "Warning threshold for return value"
                }
                "-c" = {
                        value = "$hwgroup_critical$"
                        description = "Critical threshold for return value"
                }
                "-s" = {
                        value = "$hwgroup_sensor$"
                        description = "Check the given sensor ID"
                }
                "-o" = {
                        value = "$hwgroup_output$"
                        description = "Check the given relay output ID"
                }
                "-d" = {
                        value = "$hwgroup_contact$"
                        description = "Check the given dry contact ID"
                }
                "-P" = {
                        value = "$hwgroup_snmp_version$"
                        description = "SNMP Version to use"
                }
                "-C" = {
                        value = "$hwgroup_community$"
                        description = "SNMP community string ($CHECK_HWGROUP_COMMUNITY)"
                }
                "--v3-username" = {
                        value = "$hwgroup_snmp_username$"
                        description = "SNMPv3 username"
                }
                "--v3-auth-proto" = {
                        value = "$hwgroup_snmp_auth_proto$"
                        description = "SNMPv3 authentication protocol (MD5|SHA|SHA224|SHA256|SHA384|SHA512)"
                }
                "--v3-auth-password" = {
                        value = "$hwgroup_snmp_auth_password$"
                        description = "SNMPv3 authentication password ($CHECK_HWGROUP_V3_AUTH_PASS)"
                }
                "--v3-priv-proto" = {
                        value = "$hwgroup_snmp_priv_proto$"
                        description = "SNMPv3 privacy protocol (DES|AES|AES192|AES256)"
                }
                "--v3-priv-password" = {
                        value = "$hwgroup_snmp_priv_password$"
                        description = "SNMPv3 privacy password ($CHECK_HWGROUP_V3_PRIV_PASS)"
                }
                "-t" = {
                        value = "$hwgroup_timeout$"
                        description = "Timeout for the connection"
                }
                "-r" = {
                        value = "$hwgroup_retries$"
                        description = "Retries for the connection"
                }
        }
        vars.hwgroup_hostname = "$address$"
}